manager_user:
    resource: "@ManagerUserBundle/Resources/config/routing.yml"
    prefix:   /

manager_commercial:
    resource: "@ManagerCommercialBundle/Resources/config/routing.yml"
    prefix:   /

