parameters:
#    manager_user.example.class: Manager\UserBundle\Example

services:
#    manager_user.example:
#        class: %manager_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
