admin_range:
    pattern:  /
    defaults: { _controller: "ManagerCommercialBundle:Rang:index" }

admin_range_show:
    pattern:  /{id}/show
    defaults: { _controller: "ManagerCommercialBundle:Rang:show" }

admin_range_new:
    pattern:  /new
    defaults: { _controller: "ManagerCommercialBundle:Rang:new" }

admin_range_create:
    pattern:  /create
    defaults: { _controller: "ManagerCommercialBundle:Rang:create" }
    requirements: { _method: post }

admin_range_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ManagerCommercialBundle:Rang:edit" }

admin_range_update:
    pattern:  /{id}/update
    defaults: { _controller: "ManagerCommercialBundle:Rang:update" }
    requirements: { _method: post|put }

admin_range_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ManagerCommercialBundle:Rang:delete" }
    requirements: { _method: post|delete }
